2025-05-09 07:16:39,865 - ERROR - no_search方法在数据集movielens-1m上 发生异常: No such file or directory (os error 2): ./exp_save//fea_dim/no_search-movielens-1m-widedeep-200.csv
2025-05-09 07:16:39,866 - ERROR - Traceback (most recent call last):
  File "/root/code/ShuffleDim/search_and_retrain.py", line 291, in <module>
    retrain_stage_main(args,seed, fs_seed )
  File "/root/code/ShuffleDim/search_and_retrain.py", line 116, in retrain_stage_main
    fea_df = pl.read_csv(fea_dim_path).sort(by='fea')
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/io/csv/functions.py", line 500, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/io/csv/functions.py", line 646, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2): ./exp_save//fea_dim/no_search-movielens-1m-widedeep-200.csv

2025-05-09 07:16:43,770 - ERROR - no_search方法在数据集movielens-1m上 发生异常: No such file or directory (os error 2): ./exp_save//fea_dim/no_search-movielens-1m-widedeep-200.csv
2025-05-09 07:16:43,770 - ERROR - Traceback (most recent call last):
  File "/root/code/ShuffleDim/search_and_retrain.py", line 291, in <module>
    retrain_stage_main(args,seed, fs_seed )
  File "/root/code/ShuffleDim/search_and_retrain.py", line 116, in retrain_stage_main
    fea_df = pl.read_csv(fea_dim_path).sort(by='fea')
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/io/csv/functions.py", line 500, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/polars/io/csv/functions.py", line 646, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2): ./exp_save//fea_dim/no_search-movielens-1m-widedeep-200.csv

2025-05-10 05:05:57,001 - ERROR - no_search方法在数据集criteo上 发生异常: CUDA out of memory. Tried to allocate 620.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 182.81 MiB is free. Including non-PyTorch memory, this process has 23.46 GiB memory in use. Of the allocated memory 22.38 GiB is allocated by PyTorch, and 639.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2025-05-10 05:05:57,005 - ERROR - Traceback (most recent call last):
  File "/root/code/ShuffleDim/search_and_retrain.py", line 286, in <module>
    retrain_stage_main(args,seed, fs_seed )
  File "/root/code/ShuffleDim/search_and_retrain.py", line 170, in retrain_stage_main
    Val_AUC = trainer.fit(train_data, val_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/code/ShuffleDim/common/fs_trainer.py", line 182, in fit
    train_process_data = self.train_one_epoch(train_data, epoch_i,val_data,val_dataloader)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/code/ShuffleDim/common/fs_trainer.py", line 117, in train_one_epoch
    self.optimizers['optimizer_bb'].step()
  File "/root/miniconda3/lib/python3.11/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/optim/adam.py", line 166, in step
    adam(
  File "/root/miniconda3/lib/python3.11/site-packages/torch/optim/adam.py", line 316, in adam
    func(params,
  File "/root/miniconda3/lib/python3.11/site-packages/torch/optim/adam.py", line 579, in _multi_tensor_adam
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 620.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 182.81 MiB is free. Including non-PyTorch memory, this process has 23.46 GiB memory in use. Of the allocated memory 22.38 GiB is allocated by PyTorch, and 639.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

